name: "Production CI/CD - Create Release Image"

on:
  push:
    tags:
      # Run on every tag matching this pattern (e.g. v1.4.0)
      - v[0-9]*.[0-9]*.[0-9]*
      - "!v[0-9]*.[0-9]*.[0-9]*-rc.[0-9]*"

permissions:
  contents: read

jobs:
  quality_checks:
    uses: ./.github/workflows/ci.yaml

  prepare_metadata:
    runs-on: ubuntu-latest
    needs: quality_checks
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.ref }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5.8.0
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          tags: |
            type=ref,event=tag,enable=true

          flavor: |
            latest=true

          labels: |
            org.opencontainers.image.title=${{ github.event.repository.name }}
            org.opencontainers.image.description=${{ github.event.repository.description }}
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.clone_url }}
            org.opencontainers.image.version=${{ github.ref_name }}
            org.opencontainers.image.revision=${{ github.sha }}

  build_image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    environment: production
    needs: [quality_checks, prepare_metadata]
    outputs:
      image-url: ghcr.io/${{ github.repository_owner}}/${{ github.repository }}:${{ github.ref_name }}
      image-id: ${{ steps.build.outputs.imageid }}
      digest: ${{ steps.build.outputs.digest }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.ref }}

      - name: Generate env file
        run: |
          echo "BASE_URL=${{ vars.BASE_URL }}" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          platforms: linux/amd64

      - name: Restore Docker cache
        uses: actions/cache@v4.2.4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GHCR
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          push: true
          tags: ${{ needs.prepare_metadata.outputs.tags }}
          labels: ${{ needs.prepare_metadata.outputs.labels }}
          platforms: linux/amd64
          provenance: false
          sbom: false
          cache-from: |
            type=gha
            type=local,src=/tmp/.buildx-cache

          cache-to: |
            type=gha,mode=max
            type=local,dest=/tmp/.buildx-cache-updated,mode=max

          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Update cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-updated /tmp/.buildx-cache
